import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import ThemeToggle from "@/app/components/ThemeToggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Script id="theme-script" strategy="beforeInteractive">
          {`
            (function() {
              var storedTheme = localStorage.getItem('theme');
              var systemPrefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
              
              var initialTheme = storedTheme === 'dark' || 
                (storedTheme !== 'light' && systemPrefersDark) ? 'dark' : 'light';
              
              if (initialTheme === 'dark') {
                document.documentElement.classList.add('dark');
              }
            })();
          `}
        </Script>
      </head>
      <body
        className={`${inter.className} bg-white text-gray-900 dark:bg-gray-900 dark:text-gray-100 transition-colors duration-300`}
      >
        <ThemeToggle />

        {children}
      </body>
    </html>
  );
}
